### ISSUE TITLE
Fatal error when using Elementor Theme Builder

### ISSUE THREAD

**Issue by wmacmill** [mcguffin/the-paste#35]
When using Elementor we're getting a fatal error when The Paste is installed. To replicate:
- Install Elementor & The Paste
- Attempt to open Elementor Theme Builder (will cause the fatal error)

Below are details:

An error of type E_ERROR was caused in line 129 of the file /home/nginx/domains/[/public/wp-content/plugins/the-paste/include/ThePaste/Admin/Admin.php](/public/wp-content/plugins/the-paste/include/ThePaste/Admin/Admin.php). Error message: Uncaught Error: Call to a member function enqueue() on null in /home/nginx/domains/[/public/wp-content/plugins/the-paste/include/ThePaste/Admin/Admin.php:129](/public/wp-content/plugins/the-paste/include/ThePaste/Admin/Admin.php:129)
Stack trace:
#0 /home/nginx/domains/[/public/wp-includes/class-wp-hook.php(308)](/public/wp-includes/class-wp-hook.php(308)): ThePaste\Admin\Admin->enqueue_assets()
#1 /home/nginx/domains/[/public/wp-includes/class-wp-hook.php(332)](/public/wp-includes/class-wp-hook.php(332)): WP_Hook->apply_filters()
#2 /home/nginx/domains/[/public/wp-includes/plugin.php(517)](/public/wp-includes/plugin.php(517)): WP_Hook->do_action()
#3 /home/nginx/domains/[/public/wp-includes/media.php(4747)](/public/wp-includes/media.php(4747)): do_action()
#4 /home/nginx/domains/[/public/wp-content/plugins/elementor/app/modules/onboarding/module.php(460)](/public/wp-content/plugins/elementor/app/modules/onboarding/module.php(460)): wp_enqueue_media()
#5 /home/nginx/domains/[/public/wp-includes/class-wp-hook.php(308)](/public/wp-includes/class-wp-hook.php(308)): Elementor\App\Modules\Onboarding\Module->Elementor\App\Modules\Onboarding\{closure}()
#6 /home/nginx/domains/[/public/wp-inclu](/public/wp-inclu)

**Comment by mcguffin** [comment]
fixed with #36
