### ISSUE TITLE
After you paste the image, upload it automatically.

### ISSUE THREAD

**Issue by mean-cj** [mcguffin/the-paste#37]
Hi Dev

thank you for your plugin.

Please add the fearure
"After paste the image, upload it automatically."

**Comment by mcguffin** [comment]
Just enable this button in the editor toolbar:
<img width="67" alt="grafik" src="https://github.com/mcguffin/the-paste/assets/402988/6269cc06-2978-4b0f-8a19-6642f117f4ba">
