### ISSUE TITLE
when uploading images, some will remain as BASE64 

### ISSUE THREAD

**Issue by oferlaor** [mcguffin/the-paste#39]
I upload an image, but when I randomly check, a few images sometimes are left as base64 in the post content instead.

This can be a big problem as it shows up on RSS feeds and other locations.

If upload fails, it should indicate this or remove the image but not keep it as BASE64

**Comment by mcguffin** [comment]
Small images are keep as Base64, bigger ones get uploaded.
To upload all images, enable this button in classic editor:
<img width="66" alt="grafik" src="https://github.com/mcguffin/the-paste/assets/402988/f9ef7ce1-1431-4c15-954a-00f5a8b28d8a">

**Comment by oferlaor** [comment]
I do. The problem is some occasionally are not. Is there a config that doesn’t allow users to turn the upload off. I think maybe it’s a communication issue or that some of my blog writers clicked on the button without noticing. Best regards,Ofer LaOrOn 23 Sep 2023, at 14:17, Jörn Lund ***@***.***> wrote:﻿
Small images are keep as Base64, bigger ones get uploaded.
To upload all images, enable this button in classic editor:

**Comment by mcguffin** [comment]
In Version 2 data URI images are optional (in your user profile) and disabled by default.

**Comment by oferlaor** [comment]
It should be controlled on  admin or plugin level, I think. 

Is version 2 available?
