### ISSUE TITLE
Critical Error when trying to access User Profile

### ISSUE THREAD

**Issue by alexandramclarty** [mcguffin/the-paste#42]
I love this plugin! However, recently it’s started causing a critical error when trying to access the Edit User page. 

![Capture](https://github.com/mcguffin/the-paste/assets/66077210/4df8e906-2f8b-41a0-b114-272a40afa156)

This happens even with all other plugins disabled and when using a default Twenty Twenty theme.

Is there any resolution for this?

Thank you!

**Comment by alexandramclarty** [comment]
Looks like some kind person has fixed this in their own fork! For anyone else with this issue, you can [grab their fixed version here](https://github.com/mcguffin/the-paste):
![Capture](https://github.com/mcguffin/the-paste/assets/66077210/fb5fcdff-4abf-4c2b-925e-f6242d3cb029)

I hope this plugin is still being supported. The lack of response here and in the WordPress support forum is concerning.

**Comment by mcguffin** [comment]
fixed with #41
