### ISSUE TITLE
There was a critical error after update to 2.0.1 (2.0.0 in changelog?).

### ISSUE THREAD

**Issue by Aurorum-Studio** [mcguffin/the-paste#44]
Hi, 

  I face a critical error after update to the newest version, and the admin dashboard is down because of the error. Everything went ok when I restored my backup which is not using the updated "The-Paste". I even tried to update again, and exactly the same error occured. Here is the info in error log. Private information is replaced with "*". I'm not very sure why the function "wp_is_mobile()" is undefined, since I read this in a wp official document before, but I can't test it myself since the website I'm operating can't be down, and I'm too busy. I'll keep using the old version until there is a solution, I really like the plugin, and appreciate your work. Hope to receive a reply soon.

Best regards,
Xavier

```[25-Sep-2023 16:39:54 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function ThePaste\Admin\wp_is_mobile() in /***/wp-content/plugins/the-paste/include/ThePaste/Admin/Admin.php:28
Stack trace:
#0 /***/wp-content/plugins/the-paste/include/ThePaste/Core/Singleton.php(28): ThePaste\Admin\Admin->__construct()
#1 /***/wp-content/plugins/the-paste/index.php(45): ThePaste\Core\Singleton::instance()
#2 /***/wp-settings.php(407): include_once('/***')
#3 /***/wp-config.php(118): require_once('/***')
#4 /***/wp-load.php(50): require_once('/***')
#5 /***/wp-admin/admin.php(34): require_once('/***')
#6 /***/wp-admin/index.php(10): require_once('/***')
#7 {main}
  thrown in /***/wp-content/plugins/the-paste/include/ThePaste/Admin/Admin.php on line 28
`

**Comment by Aurorum-Studio** [comment]
BTW, I'm using WordPress 6.7.1, the lastest version of WordPress, and my PHP version is ok for the requirements of the plugin.

**Comment by mcguffin** [comment]
Do you work in a Multisite, and is the plugin network enabled?
WP is defining `wp_is_mobile()` (in`wp-includes/vars.php`) *after* mu- and network plugins are loaded, so this could be an explaination.

**Comment by Aurorum-Studio** [comment]
Yes, I'm using a Multisite network, I have reinstalled with the updated version (2.0.2), and everything works fine right now. Thank you.🦊
