### ISSUE TITLE
Problem after installing The Paste 2+

### ISSUE THREAD

**Issue by Gnoztis** [mcguffin/the-paste#46]
I use the classic editor and additionally the Advanced Editor Tools plugin (TinyMCE).

After installing The Paste 2 the background of creating new posts became gray, if you disable the plugin, everything returns to normal.

This creates certain inconveniences when writing new posts.
Installing 2.0.3 didn't solve the problem

**Comment by mcguffin** [comment]
Oops, apologies. That was a debugging artefact!
Fixed in 2.0.4...
