### ISSUE TITLE
Problem when pasting from Microsoft exel

### ISSUE THREAD

**Issue by Gnoztis** [mcguffin/the-paste#49]
Version used: The Paste 2.0.5

When I paste information from Microsoft Excel when writing a post, The Paste inserts an image instead of a table.

I know that Microsoft Exel, when copying to the clipboard, puts it into many formats, including as an image.
But can something be done about it? It causes some problems when writing texts with tables.

**Comment by mcguffin** [comment]
Hi,
You can turn off Classic Editor support (aka. tinymce) in your user profile.

2.0.6 will come with a toolbar button allowing you to switch file pasting on and off. 
![](https://raw.githubusercontent.com/mcguffin/the-paste/master/.wporg/screenshot-1.png)
