### ISSUE TITLE
Critical error on editor

### ISSUE THREAD

**Issue by mananxy** [mcguffin/the-paste#62]
When I enable The Paste on my wordpress blog. The editor stops working . 

Wordpress version : 6.5.3
The paste version : latest 

Screenshot : 
![image](https://github.com/mcguffin/the-paste/assets/107296833/c1e9408c-f32c-45f9-ab16-27ac86753c9c)

**Comment by mcguffin** [comment]
@mananxy Thanks for the report. "Critical error" is a very general description of what's going wrong.
Any chance to get a meaningful error message?
Possibly with [`WP_DEBUG` set to`true`](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/#example-wp-config-php-for-debugging)?
Thanks.

**Comment by mananxy** [comment]
Thanks for looking into it. Here's what I found from a debug log . 

![image](https://github.com/mcguffin/the-paste/assets/107296833/69bc0fb7-7f08-45f7-b62e-94c6ccdeb596)
